### ISSUE TITLE
0.2.2 error "IndexError: index 0 is out of bounds for axis 0 with size 0"

### ISSUE THREAD

**Issue by shotgunmario** [cubicibo/SUPer#13]
Hello, there seems to have been something that changed from 0.2.2 up from 0.2.1. The newest version is crashing when my subtitles png's seem to be over a certain size. They failed at both 1920x1080 and 1250x200, yet 900x150 work. When I downgrade to 0.2.1 the 1250x200 work fine; it seems to be some sort of python array error.

Wonderful tool, I hope this helps.

**win_x64_SUPer_2.2.exe output:**
```
> Loading...
>  SUPui: INFO : SUPer v0.2.2, (c) cubicibo
>  SUPui: INFO : Advanced image quantizer armed: libimagequant
>  SUPui: INFO : No extension given, assuming SUP.
>  SUPui: INFO : Starting optimiser process.
> Loading...
>  SUPer: INFO : Loading input BDN: //192.168.0......./subtitles/PNG-v03/BDN_Index.xml
>  SUPer: INFO : Library parameters: {'quant': ('C:\\Users\\....\\Downloads\\win_x64_SUPer_2.2\\lib\\libimagequant_x86_64.dll', None)}
>  SUPer: IINF : Parameters: quality_factor=0.0:refresh_rate=1.0:scale_fps=False:quantize_lib=3:bt_colorspace=bt709:enforce_dts=True:no_overlap=True:full_palette=True:output_all_formats=True:normal_case_ok=False:insert_acquisitions=0:ts_long=False:max_kbps=16000:log_to_file=0
>  SUPer: IINF : BDN metadata: 1920x1080, FPS=23.976, DF=False, 241 valid events.
>  SUPer: INFO : NDF NTSC detected: scaling all timestamps by 1.001.
>  SUPer: INFO : Finding epochs...
>  SUPer: INFO : Identified epoch 00:01:26:21->00:02:44:16, 20->20 event(s):
>  SUPer: INFO :  => Screen layout: 2 window(s), analyzing objects...
>   0%|                                                                                           | 0/20 [00:00<?, ?it/s]Process SUPinternal:
> Traceback (most recent call last):
>   File "multiprocessing\process.py", line 314, in _bootstrap
>   File "multiprocessing\process.py", line 108, in run
>   File "supergui.py", line 188, in from_bdnxml
>   File "SUPer\interface.py", line 151, in optimise
>   File "SUPer\render2.py", line 370, in analyze
>   File "SUPer\render2.py", line 633, in _convert
>   File "SUPer\render2.py", line 411, in _generate_acquisition_ds
>   File "SUPer\optim.py", line 295, in solve_and_remap
> IndexError: index 0 is out of bounds for axis 0 with size 0
>   0%|                                                                                           | 0/20 [00:00<?, ?it/s]
>  SUPui: INFO : Closed gracefully SUPer process.
> 
```
**Sample of my BDN.xml** (all subtitles are being rendered out of adobe after effects, so all 241 have the same size.

```
<?xml version="1.0" encoding="utf-8"?>
<BDN Version="0.93" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BD-03-006-0093b BDN File Format.xsd">
  <Description>
    <Name Title="subtitle_exp" Content="" />
    <Language Code="eng" />
    <Format VideoFormat="1080p" FrameRate="23.976" DropFrame="false" />
    <Events Type="Graphic" FirstEventInTC="00:01:26:21" LastEventOutTC="01:33:20:00" NumberofEvents="241" />
  </Description>
  <Events>
    <Event InTC="00:01:26:21" OutTC="00:01:32:12" Forced="false">
  <Graphic Width="1250" Height="200" X="335" Y="830">0001.png</Graphic>
</Event>
<Event InTC="00:01:32:12" OutTC="00:01:34:12" Forced="false">
  <Graphic Width="1250" Height="200" X="335" Y="830">0002.png</Graphic>
</Event>
<Event InTC="00:01:34:12" OutTC="00:01:36:09" Forced="false">
  <Graphic Width="1250" Height="200" X="335" Y="830">0003.png</Graphic>
</Event>
<Event InTC="00:01:36:09" OutTC="00:01:40:09" Forced="false">
  <Graphic Width="1250" Height="200" X="335" Y="830">0004.png</Graphic>
</Event>
</Events>
</BDN>
```

**Comment by cubicibo** [comment]
Hi,

Thank you for filling this issue. Indeed, due to an oversight, function `solve_and_remap` attempts to read a potentially empty array (no transparency in bitmap) under some conditions (fewer colours used than total available, no padding inserted).
I will build **v0.2.2a** later today or tomorrow, I want to add in another parameter to tune some behaviour.
When the test build is posted, I may just ask you to test again a 1920x1080 render, full screen overlays should work just as fine as smaller sizes.

**Comment by cubicibo** [comment]
Please try the v0.2.2a build here: https://github.com/cubicibo/SUPer/releases/tag/v0.2.2

**Comment by shotgunmario** [comment]
That worked! Thanks for building this great tool!
